# Generated by Django 5.1.4 on 2026-08-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoriaVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operador_email', models.EmailField(help_text='E-mail do operador/superusuário que executou a ação', max_length=255)),
                ('ip_origem', models.GenericIPAddressField(blank=True, help_text='Endereço IP de origem da requisição', null=True)),
                ('acao', models.CharField(choices=[('CRIAR_PLANO', 'Criação de plano'), ('EDITAR_PLANO', 'Edição de plano'), ('DESATIVAR_PLANO', 'Desativação de plano'), ('PROVISIONAR_CLINICA', 'Provisionamento de clínica'), ('BLOQUEAR_CLINICA', 'Bloqueio de clínica'), ('DESBLOQUEAR_CLINICA', 'Desbloqueio de clínica'), ('EXPURGAR_CLINICA', 'Expurgo de clínica (drop schema)'), ('RESET_SENHA_ADMIN', 'Reset de senha do admin da clínica'), ('IMPERSONATE', 'Acesso de suporte (impersonate)'), ('PARAMETRIZACAO', 'Alteração de parâmetros (Google/WhatsApp)'), ('STUDIO_QUERY', 'Execução de query no Database Studio'), ('CELERY_TRIGGER', 'Disparo manual de tarefa Celery'), ('CELERY_CONFIG', 'Alteração de agendamento Celery Beat'), ('OUTRO', 'Outra ação administrativa')], default='OUTRO', max_length=50)),
                ('schema_alvo', models.CharField(blank=True, default='public', help_text='Schema sobre o qual a ação foi executada', max_length=100)),
                ('detalhes', models.JSONField(blank=True, default=dict, help_text='Dados contextuais da ação (payload, query SQL, linhas afetadas, etc.)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de auditoria do vendor',
                'verbose_name_plural': 'Registros de auditoria do vendor',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['operador_email', '-criado_em'], name='plataforma__operado_95b8d2_idx'), models.Index(fields=['schema_alvo', '-criado_em'], name='plataforma__schema__a0051c_idx'), models.Index(fields=['acao', '-criado_em'], name='plataforma__acao_dabb85_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegistroErroOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_tenant', models.CharField(help_text='Schema da clínica onde o erro ocorreu', max_length=100)),
                ('nivel', models.CharField(choices=[('WARNING', 'Aviso'), ('ERROR', 'Erro'), ('CRITICAL', 'Crítico')], default='ERROR', max_length=20)),
                ('endpoint', models.CharField(blank=True, help_text='URL / endpoint da requisição que falhou', max_length=255)),
                ('metodo', models.CharField(blank=True, help_text='Método HTTP (GET, POST, etc.)', max_length=10)),
                ('mensagem', models.TextField(help_text='Mensagem resumida do erro')),
                ('traceback', models.TextField(blank=True, help_text='Stack trace completo da exceção')),
                ('detalhes', models.JSONField(blank=True, default=dict, help_text='Contexto adicional (payload, user_id, headers sanitizados)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de erro operacional',
                'verbose_name_plural': 'Registros de erros operacionais',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['schema_tenant', '-criado_em'], name='plataforma__schema__ecd608_idx'), models.Index(fields=['nivel', '-criado_em'], name='plataforma__nivel_f34b3c_idx')],
            },
        ),
    ]
