# Generated by Django 5.1.4 on 2026-08-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_admin', '0002_seed_periodic_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperadorMFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail do operador')),
                ('secret', models.CharField(help_text='Segredo TOTP (base32)', max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '2FA de operador (Vendor)',
                'verbose_name_plural': '2FA de operadores (Vendor)',
            },
        ),
    ]
