# Generated by Django 5.1.4 on 2026-08-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_admin', '0003_operadormfa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoLoginVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token_min', models.PositiveIntegerField(default=30, help_text='Duração do access token em minutos (renovação automática). 5–240.')),
                ('refresh_token_horas', models.PositiveIntegerField(default=24, help_text='Duração da sessão (refresh token) em horas. 1–720 (30 dias).')),
                ('rotacionar_refresh', models.BooleanField(default=False, help_text='Rotaciona o refresh a cada uso (mais seguro).')),
                ('login_max_tentativas', models.PositiveIntegerField(default=5, help_text='Tentativas por IP antes de bloquear. 3–20.')),
                ('login_bloqueio_min', models.PositiveIntegerField(default=15, help_text='Tempo de bloqueio após exceder as tentativas, em minutos. 1–240.')),
                ('impersonate_validade_min', models.PositiveIntegerField(default=60, help_text='Validade do token de suporte em minutos. 5–240.')),
                ('impersonate_read_only_padrao', models.BooleanField(default=True, help_text='Suporte começa em modo somente-leitura por padrão.')),
                ('exigir_2fa_todos', models.BooleanField(default=False, help_text='Exige 2FA de TODOS os operadores (bloqueia login sem 2FA configurado).')),
                ('throttle_vendor_login', models.CharField(default='30/min', max_length=20)),
                ('throttle_impersonate', models.CharField(default='30/min', max_length=20)),
                ('throttle_studio', models.CharField(default='60/min', max_length=20)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Login & Sessão (Vendor)',
                'verbose_name_plural': 'Configurações de Login & Sessão (Vendor)',
            },
        ),
    ]
