# Generated by Django 5.1.4 on 2026-09-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_admin', '0004_configuracaologinvendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoriavendor',
            name='acao',
            field=models.CharField(choices=[('CRIAR_PLANO', 'Criação de plano'), ('EDITAR_PLANO', 'Edição de plano'), ('DESATIVAR_PLANO', 'Desativação de plano'), ('PROVISIONAR_CLINICA', 'Provisionamento de clínica'), ('BLOQUEAR_CLINICA', 'Bloqueio de clínica'), ('DESBLOQUEAR_CLINICA', 'Desbloqueio de clínica'), ('EXPURGAR_CLINICA', 'Expurgo de clínica (drop schema)'), ('RESET_SENHA_ADMIN', 'Reset de senha do admin da clínica'), ('IMPERSONATE', 'Acesso de suporte (impersonate)'), ('PARAMETRIZACAO', 'Alteração de parâmetros (Google/WhatsApp)'), ('STUDIO_QUERY', 'Execução de query no Database Studio'), ('CELERY_TRIGGER', 'Disparo manual de tarefa Celery'), ('CELERY_CONFIG', 'Alteração de agendamento Celery Beat'), ('CRIAR_AVISO', 'Criação de aviso'), ('EDITAR_AVISO', 'Edição de aviso'), ('EXCLUIR_AVISO', 'Exclusão de aviso'), ('OUTRO', 'Outra ação administrativa')], default='OUTRO', max_length=50),
        ),
    ]
