# Generated by Django 5.1.15 on 2026-09-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_admin', '0006_alter_operadormfa_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAvisoVencimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_antecedencia', models.PositiveSmallIntegerField(default=15, help_text='Dias antes do vencimento em que o aviso passa a aparecer pro tenant. 1–90.')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Aviso de Vencimento',
                'verbose_name_plural': 'Configurações de Aviso de Vencimento',
            },
        ),
    ]
