# Generated by Django 5.1.4 on 2026-08-16 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedimentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimento',
            name='retorno_meses',
        ),
    ]
