# Generated by Django 5.1.4 on 2026-08-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimentos', '0002_remove_procedimento_retorno_meses'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
