# Generated by Django 5.1.4 on 2026-07-24 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('numero', models.CharField(blank=True, max_length=50)),
                ('operadora', models.CharField(max_length=100)),
                ('competencia', models.CharField(blank=True, help_text='Referência MM/AAAA', max_length=7)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('ENVIADA', 'Enviada'), ('PAGA', 'Paga'), ('GLOSADA', 'Glosada')], default='ABERTA', max_length=20)),
                ('data_emissao', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita (a receber)'), ('DESPESA', 'Despesa (a pagar)')], max_length=10)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago/Recebido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('fatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='financeiro.fatura')),
            ],
            options={
                'verbose_name': 'Lançamento financeiro',
                'verbose_name_plural': 'Lançamentos financeiros',
                'ordering': ['-criado_em'],
            },
        ),
    ]
