# Generated by Django 5.1.4 on 2026-07-24 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_consulta_valor'),
        ('financeiro', '0001_initial'),
        ('pacientes', '0005_alter_paciente_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='agenda.consulta'),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='guia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='pacientes.guia'),
        ),
    ]
