# Generated by Django 5.1.4 on 2026-08-30 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_fornecedor_movimentacaoestoque_lancamento_financeiro_and_more'),
        ('financeiro', '0002_lancamentofinanceiro_consulta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('PIX', 'Pix'), ('BOLETO', 'Boleto'), ('CARTAO', 'Cartão'), ('DINHEIRO', 'Dinheiro'), ('TRANSFERENCIA', 'Transferência')], max_length=20),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='estoque.fornecedor'),
        ),
    ]
