# Generated by Django 5.1.4 on 2026-08-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_lancamentofinanceiro_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='numero_parcela',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='total_parcelas',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
