# Generated by Django 5.1.4 on 2026-07-19 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoOdontologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('operadora', models.CharField(max_length=100)),
                ('numero_carteirinha', models.CharField(blank=True, max_length=50)),
                ('validade', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('SUSPENSO', 'Suspenso'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=20)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Plano odontológico',
                'verbose_name_plural': 'Planos odontológicos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
