# Generated by Django 5.1.4 on 2026-07-19 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_planoodontologico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('numero_guia', models.CharField(max_length=50)),
                ('procedimento', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('EMITIDA', 'Emitida'), ('AUTORIZADA', 'Autorizada'), ('EXECUTADA', 'Executada'), ('GLOSADA', 'Glosada'), ('PAGA', 'Paga')], default='EMITIDA', max_length=20)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias', to='pacientes.planoodontologico')),
            ],
            options={
                'verbose_name': 'Guia',
                'verbose_name_plural': 'Guias',
                'ordering': ['-criado_em'],
            },
        ),
    ]
