# Generated by Django 5.1.4 on 2026-07-20 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_anamnese'),
        ('pacientes', '0003_guia'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias', to='agenda.consulta'),
        ),
    ]
