# Generated by Django 5.1.4 on 2026-08-01 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0001_initial'),
        ('pacientes', '0005_alter_paciente_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoodontologico',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planos', to='convenios.convenio'),
        ),
    ]
