# Generated by Django 5.1.4 on 2026-08-02 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentistas', '0001_initial'),
        ('pacientes', '0007_backfill_convenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='dentista_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_responsavel', to='dentistas.dentista'),
        ),
    ]
