# Generated by Django 5.1.4 on 2026-08-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentistas', '0001_initial'),
        ('pacientes', '0008_paciente_dentista_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='dentistas_compartilhados',
            field=models.ManyToManyField(blank=True, related_name='pacientes_compartilhados', to='dentistas.dentista'),
        ),
    ]
