# Generated by Django 5.1.4 on 2026-08-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_paciente_dentistas_compartilhados'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='dentes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
