# Generated by Django 5.1.4 on 2026-07-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='razao_social',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clinica',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
