# Generated by Django 5.1.4 on 2026-07-19 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
        ('tenants', '0003_tenant_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='plano_assinatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinicas', to='plataforma.planoassinatura'),
        ),
    ]
