# Generated by Django 5.1.4 on 2026-08-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_clinica_plano_assinatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='gateway_customer_id',
            field=models.CharField(blank=True, help_text='ID do cliente no gateway de pagamentos (Asaas/Stripe)', max_length=100),
        ),
        migrations.AddField(
            model_name='clinica',
            name='gateway_subscription_id',
            field=models.CharField(blank=True, help_text='ID da assinatura recorrente no gateway', max_length=100),
        ),
        migrations.AddField(
            model_name='clinica',
            name='override_limite_dentistas',
            field=models.PositiveIntegerField(blank=True, help_text='Override manual do limite de dentistas (ignora plano se definido)', null=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='override_limite_usuarios',
            field=models.PositiveIntegerField(blank=True, help_text='Override manual do limite de usuários (ignora plano se definido)', null=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='override_recursos',
            field=models.JSONField(blank=True, default=dict, help_text='Overrides de flags de módulos/recursos específicos para esta clínica'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='status_assinatura',
            field=models.CharField(choices=[('TRIAL', 'Em período de testes'), ('ATIVA', 'Assinatura ativa'), ('INADIMPLENTE', 'Inadimplente / Pagamento pendente'), ('CANCELADA', 'Cancelada')], default='ATIVA', help_text='Estado atual da assinatura do SaaS', max_length=20),
        ),
        migrations.AddField(
            model_name='clinica',
            name='vigencia_fim',
            field=models.DateField(blank=True, help_text='Data final da vigência / vencimento da fatura atual', null=True),
        ),
    ]
