# Generated by Django 5.1.4 on 2026-08-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_clinica_gateway_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='responsavel_cpf',
            field=models.CharField(blank=True, help_text='CPF do responsável assinante', max_length=14),
        ),
        migrations.AddField(
            model_name='clinica',
            name='responsavel_email',
            field=models.EmailField(blank=True, help_text='E-mail de contato institucional do responsável', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='responsavel_nome',
            field=models.CharField(blank=True, help_text='Nome completo do responsável assinante', max_length=255),
        ),
        migrations.AddField(
            model_name='clinica',
            name='responsavel_telefone',
            field=models.CharField(blank=True, help_text='Telefone/WhatsApp do responsável', max_length=20),
        ),
    ]
