# Generated by Django 5.1.4 on 2026-08-04 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_consulta_valor'),
        ('estoque', '0002_movimentacaoestoque_consulta_consumoinsumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='consumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='estoque.consumoinsumo'),
        ),
        migrations.AddConstraint(
            model_name='consumoinsumo',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='consumo_quantidade_positiva'),
        ),
        migrations.AddConstraint(
            model_name='movimentacaoestoque',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='movimentacao_quantidade_positiva'),
        ),
    ]
