# Generated by Django 5.1.4 on 2026-08-30 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_movimentacaoestoque_consumo_and_more'),
        ('financeiro', '0002_lancamentofinanceiro_consulta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='lancamento_financeiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_estoque', to='financeiro.lancamentofinanceiro'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='subtipo',
            field=models.CharField(choices=[('AJUSTE', 'Ajuste'), ('COMPRA', 'Compra')], default='AJUSTE', max_length=10),
        ),
    ]
