# Generated by Django 5.1.4 on 2026-07-20 10:00

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dentistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredencialGoogleCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('calendar_id', models.CharField(default='primary', max_length=255)),
                ('access_token', apps.core.fields.EncryptedTextField(blank=True)),
                ('refresh_token', apps.core.fields.EncryptedTextField(blank=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('scope', models.CharField(blank=True, max_length=255)),
                ('watch_channel_id', models.CharField(blank=True, max_length=255)),
                ('watch_resource_id', models.CharField(blank=True, max_length=255)),
                ('watch_expiration', models.DateTimeField(blank=True, null=True)),
                ('dentista', models.ForeignKey(blank=True, help_text='Nulo = credencial da clínica (não de um dentista específico).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credenciais_google', to='dentistas.dentista')),
            ],
            options={
                'verbose_name': 'Credencial Google Calendar',
                'verbose_name_plural': 'Credenciais Google Calendar',
            },
        ),
    ]
