# Generated by Django 5.1.4 on 2026-07-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credencialgooglecalendar',
            name='sync_token',
            field=models.TextField(blank=True),
        ),
    ]
