# Generated by Django 5.1.4 on 2026-08-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0002_credencialgooglecalendar_sync_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSincronizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('intervalo_minutos', models.PositiveIntegerField(default=30)),
                ('confirmacao_prazo_horas', models.PositiveIntegerField(default=24)),
                ('ultima_sincronizacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuração de sincronização',
                'verbose_name_plural': 'Configurações de sincronização',
            },
        ),
    ]
