# Generated by Django 5.1.4 on 2026-08-16 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0003_configuracaosincronizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaosincronizacao',
            name='confirmacao_prazo_horas',
        ),
    ]
