# Generated by Django 5.1.4 on 2026-07-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('preco_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('limite_dentistas', models.PositiveIntegerField(blank=True, help_text='Vazio = ilimitado', null=True)),
                ('limite_usuarios', models.PositiveIntegerField(blank=True, help_text='Vazio = ilimitado', null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plano de assinatura',
                'verbose_name_plural': 'Planos de assinatura',
                'ordering': ['preco_mensal'],
            },
        ),
    ]
