# Generated by Django 5.1.4 on 2026-08-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoassinatura',
            name='limite_armazenamento_mb',
            field=models.PositiveIntegerField(default=1024, help_text='Cota em MB para uploads futuros'),
        ),
        migrations.AddField(
            model_name='planoassinatura',
            name='limite_pacientes_ativos',
            field=models.PositiveIntegerField(blank=True, help_text='Vazio = ilimitado', null=True),
        ),
        migrations.AddField(
            model_name='planoassinatura',
            name='modulo_estoque_ativo',
            field=models.BooleanField(default=True, help_text='Habilita módulo de estoque/insumos'),
        ),
        migrations.AddField(
            model_name='planoassinatura',
            name='modulo_financeiro_ativo',
            field=models.BooleanField(default=True, help_text='Habilita módulo financeiro'),
        ),
        migrations.AddField(
            model_name='planoassinatura',
            name='preco_anual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor anual com desconto (opcional)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='planoassinatura',
            name='sync_google_ativo',
            field=models.BooleanField(default=True, help_text='Habilita integração com Google Calendar'),
        ),
        migrations.AddField(
            model_name='planoassinatura',
            name='whatsapp_waha_ativo',
            field=models.BooleanField(default=True, help_text='Habilita automações de WhatsApp'),
        ),
    ]
