# Generated by Django 5.1.4 on 2026-08-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_planoassinatura_limite_armazenamento_mb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoassinatura',
            name='periodicidade',
            field=models.CharField(choices=[('MENSAL', 'Mensal'), ('ANUAL', 'Anual'), ('PERMANENTE', 'Permanente (Vitalício)')], default='MENSAL', help_text='Ciclo de cobrança/renovação padrão do plano', max_length=20),
        ),
    ]
