# Generated by Django 5.1.4 on 2026-09-06 14:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_seed_planos_padrao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('imagem_url', models.URLField(blank=True)),
                ('link_url', models.URLField(blank=True)),
                ('link_rotulo', models.CharField(blank=True, max_length=50)),
                ('publicado_em', models.DateField(default=django.utils.timezone.localdate)),
                ('dias_visibilidade', models.PositiveSmallIntegerField(default=7)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'ordering': ['ordem', '-publicado_em'],
            },
        ),
    ]
