# Generated by Django 5.1.4 on 2026-09-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_aviso'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='icone',
            field=models.CharField(choices=[('megafone', 'Megafone'), ('sparkles', 'Novidade (estrelas)'), ('presente', 'Presente'), ('sino', 'Sino'), ('foguete', 'Foguete'), ('festa', 'Comemoração'), ('ferramenta', 'Manutenção'), ('info', 'Informação')], default='megafone', help_text='Exibido no lugar da imagem quando não houver imagem_url', max_length=20),
        ),
    ]
