# Generated by Django 5.1.15 on 2026-09-07 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_aviso_icone'),
        ('tenants', '0007_dominio_apex_publico'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPagamentoAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RENOVACAO', 'Renovação'), ('TROCA_PLANO', 'Troca de plano')], max_length=20)),
                ('vigencia_anterior', models.DateField(blank=True, null=True)),
                ('vigencia_nova', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('PIX', 'Pix'), ('BOLETO', 'Boleto'), ('CARTAO', 'Cartão'), ('DINHEIRO', 'Dinheiro'), ('TRANSFERENCIA', 'Transferência')], max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('operador_email', models.EmailField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_pagamentos', to='tenants.clinica')),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plataforma.planoassinatura')),
            ],
            options={
                'verbose_name': 'Histórico de pagamento/assinatura',
                'verbose_name_plural': 'Histórico de pagamentos/assinaturas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
