# Generated by Django 5.1.4 on 2026-07-20 21:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0003_agendaevento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('dias_antecedencia', models.PositiveIntegerField(default=1)),
                ('horario_envio', models.TimeField(default=datetime.time(9, 0))),
                ('waha_session', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Configuração de notificação',
                'verbose_name_plural': 'Configurações de notificação',
            },
        ),
        migrations.CreateModel(
            name='TemplateMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('CONFIRMACAO', 'Confirmação'), ('LEMBRETE', 'Lembrete'), ('CANCELAMENTO', 'Cancelamento')], max_length=20)),
                ('corpo', models.TextField(help_text='Variáveis: {{paciente}}, {{data}}, {{hora}}, {{dentista}}')),
            ],
            options={
                'verbose_name': 'Template de mensagem',
                'verbose_name_plural': 'Templates de mensagem',
            },
        ),
        migrations.CreateModel(
            name='LogNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('canal', models.CharField(choices=[('WHATSAPP', 'WhatsApp')], default='WHATSAPP', max_length=20)),
                ('direcao', models.CharField(choices=[('ENVIADA', 'Enviada'), ('RECEBIDA', 'Recebida')], default='ENVIADA', max_length=20)),
                ('mensagem', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ENFILEIRADA', 'Enfileirada'), ('ENVIADA', 'Enviada'), ('ENTREGUE', 'Entregue'), ('LIDA', 'Lida'), ('RESPONDIDA', 'Respondida'), ('ERRO', 'Erro')], default='ENFILEIRADA', max_length=20)),
                ('resposta_paciente', models.CharField(blank=True, max_length=255)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('respondido_em', models.DateTimeField(blank=True, null=True)),
                ('payload_provedor', models.JSONField(blank=True, default=dict)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='agenda.consulta')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notificacoes.templatemensagem')),
            ],
            options={
                'verbose_name': 'Log de notificação',
                'verbose_name_plural': 'Logs de notificação',
                'ordering': ['-criado_em'],
            },
        ),
    ]
