# Generated by Django 5.1.4 on 2026-07-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lognotificacao',
            name='provider_message_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
