# Generated by Django 5.1.4 on 2026-08-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0002_lognotificacao_provider_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='enviar_agradecimento',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='numero_clinica',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='palavras_confirmacao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='palavras_recusa',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
