# Generated by Django 5.1.4 on 2026-08-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0003_configuracaonotificacao_enviar_agradecimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemensagem',
            name='tipo',
            field=models.CharField(choices=[('CONFIRMACAO', 'Confirmação'), ('AGRADECIMENTO', 'Agradecimento'), ('LEMBRETE', 'Lembrete'), ('CANCELAMENTO', 'Cancelamento')], max_length=20),
        ),
    ]
