# Generated by Django 5.1.4 on 2026-08-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0004_alter_templatemensagem_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='cancelar_horas_antes',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='cancelar_nao_confirmadas',
            field=models.BooleanField(default=False),
        ),
    ]
