# Generated by Django 5.1.4 on 2026-08-16 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0005_configuracaonotificacao_cancelar_horas_antes_and_more'),
        ('procedimentos', '0002_remove_procedimento_retorno_meses'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatemensagem',
            name='horas_antes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templatemensagem',
            name='intervalo_meses',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templatemensagem',
            name='lembrete_tipo',
            field=models.CharField(blank=True, choices=[('RECALL', 'Recall por procedimento'), ('PRE_CONSULTA', 'Aviso antes da consulta')], max_length=20),
        ),
        migrations.AddField(
            model_name='templatemensagem',
            name='procedimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates_recall', to='procedimentos.procedimento'),
        ),
    ]
