# Generated by Django 5.1.4 on 2026-08-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0006_templatemensagem_horas_antes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='mensagem_reforco',
            field=models.CharField(blank=True, help_text="Vazio = texto padrão ('Por favor, responda apenas com SIM ou NÃO.').", max_length=255),
        ),
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='reforcar_confirmacao',
            field=models.BooleanField(default=True),
        ),
    ]
