# Generated by Django 5.1.4 on 2026-08-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0007_configuracaonotificacao_mensagem_reforco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemensagem',
            name='tipo',
            field=models.CharField(choices=[('CONFIRMACAO', 'Confirmação'), ('AGRADECIMENTO', 'Agradecimento'), ('LEMBRETE', 'Lembrete'), ('CANCELAMENTO', 'Cancelamento'), ('REAGENDAMENTO', 'Reagendamento')], max_length=20),
        ),
    ]
