# Generated by Django 5.1.4 on 2026-08-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0008_alter_templatemensagem_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='enviar_reagendamento',
            field=models.BooleanField(default=True),
        ),
    ]
