# Generated by Django 5.1.4 on 2026-08-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0009_configuracaonotificacao_enviar_reagendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='enviar_cancelamento',
            field=models.BooleanField(default=True),
        ),
    ]
