# Generated by Django 5.1.4 on 2026-08-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0010_configuracaonotificacao_enviar_cancelamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='reagendamento_minutos',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
