# Generated by Django 5.1.4 on 2026-08-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0011_configuracaonotificacao_reagendamento_minutos'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='segundos_digitacao',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='simular_digitacao',
            field=models.BooleanField(default=True),
        ),
    ]
