# Generated by Django 5.1.4 on 2026-08-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0012_configuracaonotificacao_segundos_digitacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='intervalo_fila_segundos',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
