# Generated by Django 5.1.4 on 2026-07-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='papel',
            field=models.CharField(choices=[('ADMIN', 'Administrador(a)'), ('DENTISTA_GERENTE', 'Dentista Gerente'), ('DENTISTA', 'Dentista'), ('RECEPCAO', 'Recepção')], default='RECEPCAO', max_length=20),
        ),
    ]
