# Generated by Django 5.1.4 on 2026-08-22 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_migrar_papel_financeiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioMFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(help_text='Segredo TOTP (base32)', max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': '2FA de usuário',
                'verbose_name_plural': '2FA de usuários',
            },
        ),
    ]
