# Generated by Django 5.1.4 on 2026-09-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuariomfa'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissaoModuloPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('ADMIN', 'Administrador(a)'), ('DENTISTA_GERENTE', 'Dentista Gerente'), ('DENTISTA', 'Dentista'), ('RECEPCAO', 'Recepção')], max_length=20)),
                ('modulo', models.CharField(max_length=30)),
                ('ver', models.BooleanField(default=False)),
                ('criar', models.BooleanField(default=False)),
                ('editar', models.BooleanField(default=False)),
                ('excluir', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Permissão de módulo personalizada',
                'verbose_name_plural': 'Permissões de módulo personalizadas',
                'constraints': [models.UniqueConstraint(fields=('papel', 'modulo'), name='permissao_papel_modulo_unico')],
            },
        ),
    ]
