# Generated by Django 5.1.4 on 2026-09-06 20:29

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_permissaomodulopersonalizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariomfa',
            name='secret',
            field=apps.core.fields.EncryptedTextField(help_text='Segredo TOTP (base32)'),
        ),
    ]
