# Generated by Django 5.1.4 on 2026-07-20 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dentistas', '0001_initial'),
        ('pacientes', '0003_guia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('procedimento', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('EM_ATENDIMENTO', 'Em atendimento'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada'), ('FALTOU', 'Faltou')], default='AGENDADA', max_length=20)),
                ('status_confirmacao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('RECUSADA', 'Recusada'), ('SEM_RESPOSTA', 'Sem resposta')], default='PENDENTE', max_length=20)),
                ('confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('google_event_id', models.CharField(blank=True, max_length=255)),
                ('observacoes', models.TextField(blank=True)),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='dentistas.dentista')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['inicio'],
            },
        ),
    ]
