# Generated by Django 5.1.4 on 2026-07-20 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('dentistas', '0001_initial'),
        ('pacientes', '0003_guia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('queixa_principal', models.TextField(blank=True)),
                ('historico_medico', models.JSONField(blank=True, default=dict)),
                ('pressao_arterial', models.CharField(blank=True, max_length=20)),
                ('fumante', models.BooleanField(default=False)),
                ('diabetico', models.BooleanField(default=False)),
                ('gestante', models.BooleanField(default=False)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anamneses', to='agenda.consulta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anamneses', to='pacientes.paciente')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anamneses_registradas', to='dentistas.dentista')),
            ],
            options={
                'verbose_name': 'Anamnese',
                'verbose_name_plural': 'Anamneses',
                'ordering': ['-criado_em'],
            },
        ),
    ]
