# Generated by Django 5.1.4 on 2026-07-20 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_anamnese'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('google_event_id', models.CharField(blank=True, max_length=255)),
                ('calendar_id', models.CharField(default='primary', max_length=255)),
                ('etag', models.CharField(blank=True, max_length=255)),
                ('sync_token', models.CharField(blank=True, max_length=255)),
                ('ultima_sincronizacao', models.DateTimeField(blank=True, null=True)),
                ('status_sync', models.CharField(choices=[('PENDENTE', 'Pendente'), ('SINCRONIZADO', 'Sincronizado'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evento_google', to='agenda.consulta')),
            ],
            options={
                'verbose_name': 'Evento de agenda (Google)',
                'verbose_name_plural': 'Eventos de agenda (Google)',
            },
        ),
    ]
