# Generated by Django 5.1.4 on 2026-07-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_agendaevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
