# Generated by Django 5.1.4 on 2026-08-08 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_consulta_valor'),
        ('convenios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='convenios.convenio'),
        ),
    ]
