# Generated by Django 5.1.4 on 2026-08-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_consulta_convenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='anotacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='dentes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
