# Generated by Django 5.1.4 on 2026-08-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_consulta_anotacoes_consulta_dentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='confirmacao_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
