# Generated by Django 5.1.4 on 2026-08-16 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_consulta_confirmacao_token'),
        ('procedimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='procedimento_catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='procedimentos.procedimento'),
        ),
    ]
