# Generated by Django 5.1.4 on 2026-08-16 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_consulta_procedimento_catalogo'),
        ('integracoes', '0003_configuracaosincronizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaevento',
            name='credencial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='integracoes.credencialgooglecalendar'),
        ),
        migrations.AlterField(
            model_name='agendaevento',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_google', to='agenda.consulta'),
        ),
        migrations.AddConstraint(
            model_name='agendaevento',
            constraint=models.UniqueConstraint(fields=('consulta', 'credencial'), name='evento_unico_por_credencial'),
        ),
    ]
