# Generated by Django 5.1.4 on 2026-08-16 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_agendaevento_credencial_alter_agendaevento_consulta_and_more'),
        ('integracoes', '0003_configuracaosincronizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaevento',
            name='assinatura',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='EventoGoogleRemovido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('calendar_id', models.CharField(default='primary', max_length=255)),
                ('google_event_id', models.CharField(max_length=255)),
                ('credencial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remocoes_pendentes', to='integracoes.credencialgooglecalendar')),
            ],
            options={
                'verbose_name': 'Remoção pendente (Google)',
                'verbose_name_plural': 'Remoções pendentes (Google)',
            },
        ),
    ]
