# Generated by Django 5.1.4 on 2026-08-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_agendaevento_assinatura_eventogoogleremovido'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='reagendada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
