# Generated by Django 5.1.4 on 2026-08-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_consulta_reagendada_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventogoogleremovido',
            name='processado',
            field=models.BooleanField(default=False),
        ),
    ]
