# Generated by Django 5.1.4 on 2026-08-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_eventogoogleremovido_processado'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaevento',
            name='origem',
            field=models.CharField(choices=[('SISTEMA', 'Criado pelo sistema'), ('IMPORTADO', 'Importado do Google')], default='SISTEMA', max_length=20),
        ),
    ]
