# Generated by Django 5.1.4 on 2026-08-27 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_agendaevento_origem'),
        ('pacientes', '0010_guia_dentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('dentes', models.JSONField(blank=True, default=list)),
                ('anotacoes', models.TextField(blank=True)),
                ('consulta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ficha', to='agenda.consulta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichas', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Ficha',
                'verbose_name_plural': 'Fichas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
