# Generated by Django 5.1.4 on 2026-08-27 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0015_backfill_ficha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='anotacoes',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='dentes',
        ),
    ]
