# Generated by Django 5.1.4 on 2026-08-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0016_remove_consulta_dentes_anotacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='data_primeira_parcela',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('PIX', 'Pix'), ('BOLETO', 'Boleto'), ('CARTAO', 'Cartão'), ('DINHEIRO', 'Dinheiro'), ('TRANSFERENCIA', 'Transferência')], max_length=20),
        ),
        migrations.AddField(
            model_name='consulta',
            name='parcelas',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
