# Generated by Django 5.1.4 on 2026-09-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0017_consulta_data_primeira_parcela_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='status_confirmacao',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('MANUAL', 'Confirmada manualmente'), ('RECUSADA', 'Recusada'), ('SEM_RESPOSTA', 'Sem resposta')], default='PENDENTE', max_length=20),
        ),
    ]
